### ISSUE TITLE
Parsing Error On Android 6

### ISSUE THREAD

**Issue by Dev-i-l** [polymorphicshade/NewPipe#11]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Download newpipe sponsorblock
2. try to install it on android 6
3. i get a parse error

### Actual behaviour

I get parse error

### Expected behavior

it should install easily like vanilla newpipe 20.5

### Device info

 - Android version/Custom ROM version: 6
 - Device model:

**Comment by polymorphicshade** [comment]
I'm unable to reproduce this issue on my Android 6 emulator, though I'm going to leave this issue open for a while to see if others can chime in and report the same issue.

Have you tried allowing apps from unknown sources? I read somewhere that enabling this setting might fix that issue.

**Comment by Dev-i-l** [comment]
ofcourse i did enable installation from unknown sources and vanilla newpipe installs and runs fine on my device

**Comment by kavishkj** [comment]
I am also getting same parsing error on my resmi note 3 Kenzo india version running on android 6 with top of miui 10 official , stock app is working fine.

**Comment by polymorphicshade** [comment]
Oh so it looks like I can reproduce the issue if I try to install **both** vanilla NewPipe and SponsorBlock X NewPipe. I believe this is because they both have the same package id in the manifest.

This install issue should be fixed once I get the package and app name changed in this fork.

**Comment by barolo** [comment]
I'm having same issue

**Comment by polymorphicshade** [comment]
This should now be fixed in release [v0.20.6_r3](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.20.6_r3).

My testing found that by changing the applciationId in the build.gradle file, I no longer get a parsing error, but if this is still a problem I'll reopen this issue and wait until a new name and logo are decided on.

**Comment by barolo** [comment]
@polymorphicshade It is still a problem, that build didn't fix it unfortunately

**Comment by polymorphicshade** [comment]
Welp, guess I'll keep this issue open then 😅

@barolo I'll dink around the code and whatnot and make a test APK you can try in a few hours.

**Comment by polymorphicshade** [comment]
@barolo give [this APK](https://github.com/polymorphicshade/NewPipe/files/5718823/newpipe_x_sponsorblock_test.zip) a shot.
If this works, then it might not be a problem with the applicationId... 🤔

**Comment by barolo** [comment]
That one works

**Comment by polymorphicshade** [comment]
So it looks like I needed to use **both** V1 and V2 signatures on the release APK:
![image](https://user-images.githubusercontent.com/32504507/102699940-1c7b1f00-4206-11eb-81e5-7fa027b05a73.png)

I've updated the latest release with the newly signed APK.
I'll re-close this issue... for now...

**Comment by Dev-i-l** [comment]
it's fixed, now i can install both vanilla and sponsorblock newpipe at the same time, also thanks for fixing the sponsorblock lag, keep up the great work!
